project:
  type: book
  output-dir: _book

book:
  title: "R for Data Science (2e) 中文版"
  reader-mode: true

  page-footer:
    left: |
      本书中文版内容由[陆震](https://leslie-lu.github.io/)组织「OpenBioStat R for Data Science (2e) 中文版」翻译小组
      （成员：[陆震](https://leslie-lu.github.io/)、[夏鑫辛](https://github.com/kirihsia)）翻译并维护。
    right: >
      本书使用 <a href="https://quarto.org/">Quarto</a> 构建。
  cover-image: cover.jpg
  favicon: cover.jpg
  site-url: https://openbiostat.github.io/R-for-Data-Science-2e-Chinese/
  repo-url: https://github.com/openbiostat/R-for-Data-Science-2e-Chinese/
  repo-branch: main
  repo-actions: [edit, issue]
  chapters:
    - index.qmd
    - preface-2e.qmd
    
    - intro.qmd

    # # TODO: UPDATE parts and chapters
    # - part: whole-game.qmd
    #   chapters:
    #     - data-visualize.qmd
    #     - workflow-basics.qmd
    #     - data-transform.qmd
    #     - workflow-style.qmd
    #     - data-tidy.qmd
    #     - workflow-scripts.qmd
    #     - data-import.qmd
    #     - workflow-help.qmd

    # - part: visualize.qmd
    #   chapters:
    #     - layers.qmd
    #     - EDA.qmd
    #     - communication.qmd

    # - part: transform.qmd
    #   chapters:
    #     - logicals.qmd
    #     - numbers.qmd
    #     - strings.qmd
    #     - regexps.qmd
    #     - factors.qmd
    #     - datetimes.qmd
    #     - missing-values.qmd
    #     - joins.qmd

    # - part: import.qmd
    #   chapters:
    #     - spreadsheets.qmd
    #     - databases.qmd
    #     - arrow.qmd
    #     - rectangling.qmd
    #     - webscraping.qmd

    # - part: program.qmd
    #   chapters:
    #     - functions.qmd
    #     - iteration.qmd
    #     - base-R.qmd

    # - part: communicate.qmd
    #   chapters:
    #     - quarto.qmd
    #     - quarto-formats.qmd

format:
  html:
    theme:
      - cosmo
      - r4ds.scss
    code-link: true

    author-meta: "Hadley Wickham, Mine Çetinkaya-Rundel, and Garrett Grolemund 著，陆震、夏鑫辛翻译"
    include-in-header: "plausible.html"
    callout-appearance: simple

editor: source
